name: simple

services:
  app:
    image: adhari1720/simple-arya
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - "vol-simple:/app/public/images/"
    restart: always

volumes:
  vol-simple:
